# NumPy
**Num**erical **Py**thon

<img src="https://numpy.org/images/logo.svg" width="100" height="100"/>

[공식] (https://numpy.org/)


In [1]:
# numpy : 수치적 연산을 위해 최적화된 모듈
#  파이썬을 활용한 데이터 분석에서  가장 기본!
#  이 자체로도 많이 쓰이거니와, 앞으로 배울 pandas, 머신러닝 등 수많은 분야에서 기본적으로 사용하는 모듈
#  파이썬 개발자라면 꼭 익힐 필요 있다

# 수학수치 연산  (numerical python) / 합, 평균, 행렬연산 등..
# 추가적으로 scipy, statsmodel  같은 것들도 numpy 기반으로 구현됨.
# 상황에 따라, pandas 안써도 numpy 만으로도 가능.

# 기본 타입 : ndarray  (n-dimensional array) 다차원 배열 표현

# 파이썬에 list 가 있는데 굳이? 왜?  -

# numpy 를 사용하는 이유
# 1. 성능 : 성능적으로 훨~씬 빠름.
# 2. 메모리 : 훨씩 적은 메모리사용
# 3. 제공함수풍부 : 선형대수, 통계관련 여러 수치함수 제공
# 4. 수많은 모듈에서 numpy 함수명 과 기능을 그대로 사용.


In [2]:
import numpy as np

![aaa](https://statkclee.github.io/deep-learning/fig/tensor.jpg)

**Scalar** : 0차원 array (단일값)

**Vector** : 1차원 array

**Matrix** : 2차원 array

**Tensor** : 3차원(이상) array

# 1차원 array (벡터) 생성

In [3]:
# np.array(iterable)

arr1 = np.array([1, 2, 3, 4, 5])

arr1

array([1, 2, 3, 4, 5])

In [4]:
print(arr1)

[1 2 3 4 5]


In [5]:
type(arr1)

numpy.ndarray

In [6]:
# scalar (0차원 array)
np.array(10)

array(10)

In [7]:
[1, 2, 3.14, '김', True]   # list 는 원소타입이 가각 다를수 있다!

[1, 2, 3.14, '김', True]

In [8]:
# 그러나!  numpy array의 모든 원소는 '한가지 타입' 으로만 정의된다!

# shape, size, ndim, dtype 그리고 len()

In [9]:
arr1

array([1, 2, 3, 4, 5])

## shape
numpy에서는 해당 array의 크기를 알 수 있다.<br>
shape 을 확인함으로써 몇개의 데이터가 있는지, 몇 차원으로 존재하는지 등을 확인할 수 있다.<br>
위에서 arr1.shape의 결과는 (5,) 으로써, 1차원의 데이터이며 총 5라는 크기를 갖고 있음을 알 수 있다.
arr4.shape의 결과는 (4,3) 으로써, 2차원의 데이터이며 4 * 3 크기를 갖고 있는 array 이다.


In [10]:
arr1.shape

# (5,)  <- 숫자의 개수는 차원.
# 차원의 크기는 5

(5,)

## ndim  차원수

In [11]:
# 몇 차원 데이터인지?
arr1.ndim

# ndim 과 len(arr.shape) 은 같다!

1

## size : 데이터 개수

In [12]:
arr1.size

5

## len(array)
- array 는 iterable 하다!

In [13]:
len(arr1)

5

## dtype: data type

In [14]:
arr1.dtype

# dtype('int64')  정수 64bit (8byte)

dtype('int64')

In [15]:
arr2 = np.array([10, 3.14, 2, 0.12])
arr2

array([10.  ,  3.14,  2.  ,  0.12])

In [16]:
arr2.dtype

dtype('float64')

In [17]:
# numpy에서 사용되는 자료형은 아래와 같다. (자료형 뒤에 붙는 숫자는 몇 비트 크기인지를 의미한다.)

# 부호가 있는 정수 int(8, 16, 32, 64)
# 부호가 없는 정수 uint(8 ,16, 32, 64)
# 실수 float(16, 32, 64, 128)
# 복소수 complex(64, 128, 256)
# 불리언 bool
# 문자열 string_
# 파이썬 오프젝트 object
# 유니코드 unicode_

# 2차원 array 생성

In [18]:
# 2차원 array 생성
arr2 = np.array([[2, 3, 4], [1, 2, 4]])

arr2

array([[2, 3, 4],
       [1, 2, 4]])

In [19]:
arr2.shape

(2, 3)

In [20]:
arr2.ndim

2

In [21]:
# 1차원 배열의 원소는 스칼라값 (0차원)
len(arr1)

5

In [22]:
# 2차원 배열의 원소는 1차원 배열
len(arr2)

2

In [23]:
arr2.size

6

# 같은 값이라도 '차원' 이 다를 수 있다
'차원변환' 중요하다!

In [24]:
# scalar 0차원
np.array(10)


array(10)

In [25]:
# 1차원
np.array([10])


array([10])

In [26]:
# 2차원
np.array([[10]])

array([[10]])

# np.arange()
- array 생성
- range() 와 사용법 유사

In [27]:
# 0 부터 10 전까지  [0, 10)
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [30]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [31]:
np.arange(1, 10, dtype=np.int16)

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)

# astype(타입)
타입변환한 array 를 리턴 (원본 변화 없슴!)

In [32]:
d = np.arange(3, 10)
d   # dtype=int64 타입

array([3, 4, 5, 6, 7, 8, 9])

In [33]:
d.astype(np.float64)

array([3., 4., 5., 6., 7., 8., 9.])

In [34]:
# 원본은 변화 없다
d

array([3, 4, 5, 6, 7, 8, 9])

# reshape()
 - ndarray의 형태, 차원을 바꾸기 위해 사용
 - 머신러닝, 데이터 프로세싱에서 매우 자주 사용됨. (차원변환)

In [35]:
# (12,) -> (2, 6)
np.arange(12).reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [37]:
# size 안 맞으면 에러!

# np.arange(12).reshape(2, 4)


In [38]:
np.arange(12).reshape(3, 2, 2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

# np.ones, np.zeros, np.eye, np.full

In [39]:
# np.ones(shape)  1 로 채워진 array 생성, dtype=float64(기본값) 으로 생성됨

np.ones(6)  # dtype=float64 로 만들어짐.


array([1., 1., 1., 1., 1., 1.])

In [40]:
np.ones((2, 3), dtype=np.int16)


array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [41]:
# np.zeros(shape)  0 으로 채워진 array 생성, dtype=float64(기본값) 으로 생성됨
np.zeros((3, 2, 5))


array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [42]:
# np.eye(N) 단위행렬, 주대각선만 1이고 나머지는 0 인 (N,N) array 생성

np.eye(5, dtype=np.int16) # -> (5, 5) 단위 행렬


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int16)

In [43]:
# np.full(shape, fill_value) 특정값으로 채워진 array 생성

np.full((2, 3), 10)


array([[10, 10, 10],
       [10, 10, 10]])

# np.random 서브모듈

In [44]:
# rand: 0부터 1사이의 균일 분포 [0, 1)  uniform distribution
# randn: 가우시안 표준 정규 분포 (평균0, 표준편차1 인 종모양 분포)  normal distribution
# randint: 균일 분포의 정수 난수
# seed: 램덤 시드값.  고정 난수값 생성

![](https://thebook.io/img/080263/218.jpg)

In [45]:
np.random.rand(10)


array([0.58856886, 0.26093418, 0.64921407, 0.66552132, 0.81017877,
       0.33000508, 0.91659605, 0.19783543, 0.54494915, 0.57904898])

In [46]:
np.random.rand(2, 3)

array([[0.14309353, 0.30486328, 0.85275412],
       [0.24001492, 0.04883082, 0.84448773]])

In [47]:
np.random.randn(5)

array([ 0.29904924, -1.68149036,  0.77227703, -0.43302774,  0.19593748])

In [48]:
# 0 ~ 4 사이의 정수 난수 [0, 5)
np.random.randint(5)

3

In [49]:
np.random.randint(1, 10)  # [1, 10)

7

In [50]:
np.random.randint(1, 100, (3, 5, 2))

array([[[96, 88],
        [59, 19],
        [88, 60],
        [97, 17],
        [68, 75]],

       [[47, 80],
        [18, 11],
        [92, 67],
        [51, 72],
        [99, 24]],

       [[86, 15],
        [16, 62],
        [19, 27],
        [86, 32],
        [76, 32]]])

In [51]:
# seed() : 난수를 예측가능하도록 만든다.  실행할때마다 동일한 난수가 발생되도록 함.
np.random.seed(0)
np.random.rand(4)


array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

In [52]:
np.random.seed(1)
np.random.rand(4)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01])

In [53]:
#  비결정적 연산 (Non-Deterministic Operations)
#    같은 코드, 같은 입력을 줬는데도 결과가 매번 조금씩 달라지는 연산

#  결정적 연산 (Deterministic Operations)
#    같은 코드, 같은 입력, 같은 시드를 주면 결과가 동일한 연산

# 인덱싱 index
 - 파이썬 리스트와 동일한 개념으로 사용
 - tuple 을 사용하여 각 차원별 인덱스에 접근 가능
 - 인덱싱 할때마다 차원감소

In [54]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
x[0]


np.int64(0)

In [56]:
type(x[0])

numpy.int64

In [57]:
x[0].item()   # int값

0

In [58]:
x[-1], x[9]

(np.int64(9), np.int64(9))

In [59]:
x[3] = 100
x

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

In [60]:
y = np.arange(10).reshape(2, 5)
y # 2차원

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [61]:
y[0]


array([0, 1, 2, 3, 4])

In [62]:
y[0][2]

np.int64(2)

In [63]:
# tuple로 차원별 인덱싱 가능!  numpy 에선 후자의 방법을 추천!
y[0, 2]


np.int64(2)

## Advanced Indexing
- Integer array indexing

In [64]:
x = np.arange(100, 1000, 100)
x

array([100, 200, 300, 400, 500, 600, 700, 800, 900])

In [65]:
x[0]  # 차원축소된 결과!

np.int64(100)

In [66]:
x[[0]]   # 결과는 그대로 1차원이다!


array([100])

In [67]:
x[[1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0]]


array([200, 100, 100, 100, 100, 100, 200, 200, 200, 200, 100, 100, 100])

# 슬라이싱 slice
 - 리스트, 문자열 slicing과 동일한 개념으로 사용
 - tuple 을 사용하여 각 차원 별로 슬라이싱 가능
 - 슬라이싱은 차원 변화 없다

In [68]:
x

array([100, 200, 300, 400, 500, 600, 700, 800, 900])

In [69]:
x[1:7]

array([200, 300, 400, 500, 600, 700])

In [70]:
x[1:]

array([200, 300, 400, 500, 600, 700, 800, 900])

In [71]:
x[:]

array([100, 200, 300, 400, 500, 600, 700, 800, 900])

In [72]:
x[...]  # ellipsis 연산자

array([100, 200, 300, 400, 500, 600, 700, 800, 900])

In [73]:
x[::2]

array([100, 300, 500, 700, 900])

In [74]:
x[1::3]

array([200, 500, 800])

In [75]:
x[::-1]

array([900, 800, 700, 600, 500, 400, 300, 200, 100])

In [76]:
# list 의 경우 생각해보자
y = [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9],
     [10, 11, 12, 13, 14]]
y

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [77]:
y[0:1]  # 행 (axis=0) 에 대한 slicing

[[0, 1, 2, 3, 4]]

In [78]:
y[1:3]

[[5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [79]:
# 과연 아래와 같이 slicing 가능한가?
# [[1, 2, 3],
#  [6, 7, 8]]

y[:2]


[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]

In [80]:
y[:2][1:4]


[[5, 6, 7, 8, 9]]

In [81]:
# ↑ list 는 차원별 slicing 이 불가능하다!
# ↓ array 는 차원별 slicing 가능하다!

In [82]:
x = np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [83]:
x[:2][1:4]


array([[5, 6, 7, 8, 9]])

In [84]:
# array 는 차원별 slicing 가능하다!
x[:2, 1:4]


array([[1, 2, 3],
       [6, 7, 8]])

In [85]:
x[2, 1:4]


array([11, 12, 13])

---
# shape (차원) 변경하기
**차원변환**은 데이터분석 과 인공지능에서 매우 빈번하게 발생되는 작업이니만큼 자유자재로 변환할수 있어야 하고, 머리속으로 내가 변환하는 데이터의 구조가 그려지도록 익숙해져야 합니다

사용 예) 이미지 데이터 벡터화 - 이미지는 기본적으로 2차원 혹은 3차원(RGB)이나 트레이닝을 위해 1차원으로 변경하여 사용 됨

## ravel(), np.ravel()
  - [ˈrævl]
  - 다차원배열을 1차원으로 변경 (흔히 '**펼친다**'라고 말함)
  - 'order' 파라미터
    - 'C' - row 우선 변경 ,   C style
    - 'F - column 우선 변경,   Fortran style
  - ravel() 은 np 안에 일반 함수로도 있고, 혹은 ndarray 의 멤버함수로서도 존재

## flatten()
 - 다차원 배열을 1차원으로 변경
 - ravel과의 차이점:
     - copy를 생성하여 변경함(즉 원본 데이터가 아닌 복사본을 반환)
     - ndarray 의 멤버함수로만 제공됨
 - 'order' 파라미터
   - 'C' - row 우선 변경
   - 'F - column 우선 변경

In [86]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [87]:
x.ravel()  # (3, 5) -> (15,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [88]:
np.ravel(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [89]:
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## reshape 함수
 - array의 shape을 다른 차원으로 변경
 - 주의할점은 reshape한 후의 결과의 전체 원소 개수(size)와 이전 개수가 같아야 가능
 - 사용 예) 이미지 데이터 벡터화 - 이미지는 기본적으로 2차원 혹은 3차원(RGB)이나 트레이닝을 위해 1차원으로 변경하여 사용 됨
 - **-1** 값을 주어 나머지 차원을 유추하게 할수 있다

In [90]:
x2 = np.arange(36)
x2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [91]:
x2.reshape(6, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [92]:
# -1 의 차원 크기가 유추되어 reshape 된다  => (6, 6)
x2.reshape(6, -1)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [93]:
x2.reshape(6, -1, 2)  # (6, 3, 2)


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35]]])

## 차원 확장 / 제거

- 차원 확장/제거 하는 동작도 머신러닝에서 많이 사용된다.
- **reshape()** 로 차원 변환(확장/제거) 자유롭게 가능

### 차원 확장 : np.expand_dims()
- axis= 로 지정된 '차원을 추가'한다.


### 차원 자동 제거 : squeeze, np.squeeze()

- 차원 중 사이즈가 1인 것을 찾아 스칼라값으로 바꿔 해당 '차원을 제거'한다.

In [94]:
x3 = np.arange(6)  # (6,)
x3

array([0, 1, 2, 3, 4, 5])

In [95]:
# (6,) => (6, 1) 로 차원 확장
x3 = x3.reshape(6, 1)
x3

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [96]:
x3 = x3.reshape(6, 1, 1)
x3

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]]])

In [97]:
# 1차원으로 축소 (차원 제거)
x3.reshape((6,))


array([0, 1, 2, 3, 4, 5])

In [98]:
# squeeze() 사용. 차원크기가 1인 차원을 제거  (6, 1, 1) => (6,)
x3.squeeze()


array([0, 1, 2, 3, 4, 5])

In [99]:
x4 = np.arange(6).reshape((2, 1, 3, 1))
x4

array([[[[0],
         [1],
         [2]]],


       [[[3],
         [4],
         [5]]]])

In [100]:
# (2, 1, 3, 1) => (2, 3)
x4.squeeze()

array([[0, 1, 2],
       [3, 4, 5]])

In [101]:
x5 = np.arange(3)  # (3,)
x5

array([0, 1, 2])

In [102]:
# expand_dims 사용: 0번째 차원축(axis) 에 새로운 차원 추가(삽입)
y5= np.expand_dims(x5, axis=0)   # (3,) -> (1, 3)
print(y5.shape)
y5


(1, 3)


array([[0, 1, 2]])

In [103]:
x6 = np.arange(4).reshape(2, 2)
x6

array([[0, 1],
       [2, 3]])

In [104]:
# 마지막에 차원축 추가
# (2, 2) => (2, 2, 1)

y7 = np.expand_dims(x6, -1)
print(y7.shape)
y7


(2, 2, 1)


array([[[0],
        [1]],

       [[2],
        [3]]])

In [105]:
# axis 0 과 axis -1 에 새로운 차원 추가
# (2, 2) -> (1, 2, 2, 1)
y7 = np.expand_dims(x6, (0, -1))
print(y7.shape)
y7


(1, 2, 2, 1)


array([[[[0],
         [1]],

        [[2],
         [3]]]])

In [106]:
x8 = np.array([2, 0, 1, 8])  # (4,)
x8

array([2, 0, 1, 8])

In [107]:
# np.newaxis 사용
y8 = x8[np.newaxis, :]  # (4,) -> (1, 4)
print(y8.shape)
y8

(1, 4)


array([[2, 0, 1, 8]])

In [108]:
# ↑ 1차원 벡터를 row vector 로 변환한다 라고도 함.

In [109]:
# np.newaxis 사용. (4,) => (4, 1)
a2 = x8[:, np.newaxis]
print(a2.shape)
a2


(4, 1)


array([[2],
       [0],
       [1],
       [8]])

In [110]:
# ↑ 1차원 벡터를 column vector 로 변환한다 라고도 함.

# transpose, T,  swapaxes
전치행렬 (transpose matrix) , 차원 축 바꾸기

![](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbtmNz3%2FbtqDk6Xy5nh%2FD7U80E2R3fnahK00cijoY1%2Fimg.png)

In [111]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [112]:
# transpose. (3, 5) => (5, 3)
np.transpose(a)


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [113]:
# .T
a.T


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [114]:
# swapaxes() 사용. axis 0 과 axis 1 을 바꾸기
# (3, 5) => (5, 3)
np.swapaxes(a, 0, 1)


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

# 🟦 기본연산, 기본함수

In [115]:
np.random.seed(42)
x = np.arange(15).reshape(3, 5)
y = np.arange(0, 150, 10).reshape(3, 5)
y2 = np.random.rand(15).reshape(3, 5)
y3 = np.arange(15).reshape(5, 3)

In [116]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [117]:
y

array([[  0,  10,  20,  30,  40],
       [ 50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140]])

In [118]:
y2

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497]])

In [119]:
y3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## array 간 연산

In [120]:
# 리스트의 경우는 어떠했나?
a = [10, 20, 30, 40]
b = 2
c = [100, 200, 300, 400]

In [121]:
a * 2

[10, 20, 30, 40, 10, 20, 30, 40]

In [122]:
# a + b


In [123]:
a + c # list + list

[10, 20, 30, 40, 100, 200, 300, 400]

In [124]:
# array 연산은 리스트와 다르다!
# 기본적으로 '원소' 끼리 연산 (element-wise operation) 수행

In [125]:
x + y


array([[  0,  11,  22,  33,  44],
       [ 55,  66,  77,  88,  99],
       [110, 121, 132, 143, 154]])

In [126]:
x - y

array([[   0,   -9,  -18,  -27,  -36],
       [ -45,  -54,  -63,  -72,  -81],
       [ -90,  -99, -108, -117, -126]])

In [127]:
# array 와 스칼라 값 연산 가능
x + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [128]:
# 단일값만 갖고 있는 객체와는 shape 관계없이, scalar 연산 수행
x + [10]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [129]:
x + [[10]]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## axis (차원축)

In [130]:
# numpy 의 많은 함수들은 axis=  파라미터를 갖고 있습니다.
# axis (축) 은 각 '차원' 을 의미합니다.
# 1차원 array 라면  각 차원에 대한 axis 값은 0  <- 1개 입니다.
# 2차원 array 라면  각 차원에 대한 axis 값은 0, 1  <- 2개 입니다.
# 3차원 array 라면  각 차원에 대한 axis 값은 0, 1, 2  <- 3개 입니다.

# axis= 값을 명시하면 그 함수의 연산 은 해당 axis(축) 에 '따라서' 연산을 수행함

# 과연 '따라서' 의 의미가 무엇인지 실습을 통해 이해해봅시다

In [131]:
x1 = np.arange(15)
x1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [132]:
np.sum(x1)


np.int64(105)

In [133]:
np.sum(x1, axis=None)

np.int64(105)

In [134]:
x2 = x1.reshape(3, 5)
x2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [135]:
x2.shape

# (행, 열)
# (axis 0, axis 1)

(3, 5)

In [136]:
np.sum(x2) # axis=None

np.int64(105)

In [137]:
np.sum(x2, axis=0)  # (3, 5) => (5,)

# 15 = 0 + 5 + 10
#     [0,0] + [1,0] + [2,0]

array([15, 18, 21, 24, 27])

In [138]:
x2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [139]:
np.sum(x2, axis=1) # (3, 5) => (3,)

# 35 = 5  +  6  + 7  + 8  + 9
#    [1,0] + [1,1] + [1,2] + [1,3] + [1,4]

array([10, 35, 60])

In [140]:
np.sum(x2, axis=-1)

array([10, 35, 60])

In [141]:
y

array([[  0,  10,  20,  30,  40],
       [ 50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140]])

In [142]:
# max() 최댓값
np.max(y)


np.int64(140)

In [143]:
# argmax() 최댓값의 index
np.argmax(y)


np.int64(14)

In [144]:
np.max(y, axis=0)  # (3, 5) => (5,)

array([100, 110, 120, 130, 140])

In [145]:
np.argmax(y, axis=0)

array([2, 2, 2, 2, 2])

# NaN (Not a Number)
- `NaN`은 정의되지 않거나 표현할 수 없는 **수치 결과**를 의미
- Numpy 에선 보통 `np.nan` 으로 NaN 표현

In [146]:
# NaN (Not a Number : 숫자이어야 하는데 숫자가 아닌 값, 숫자로 표현할수 없는 값)
# 실무 데이터를 다루다 보면 NaN 을 엄청나게 자주 만나게 된다.
#    원본데이터의 '누락' 이라든지, DBMS 상의 null 값이라든지 등등. 여러가지 이슈로 NaN 값 발생
#    ★그래서 데이터 분석시 NaN 값을 제거 하든지 혹은 치환 하든지.. 해서 처리할줄 알아야 한다


In [147]:
np.nan


nan

## isnan : nan 판별

In [148]:
np.isnan(100)


np.False_

In [149]:
np.isnan(np.nan)

np.True_

In [150]:
import math
math.isnan(np.nan)

True

## nan 과의 연산

In [151]:
# 기본적인 수치 연산에서 NaN이 하나라도 있으면 결과가 NaN
np.nan + 10


nan

In [152]:
arr = np.array([10, 20, np.nan])
arr

array([10., 20., nan])

In [153]:
np.sum(arr)  # nan (다음에 배울 pandas 에서는 이 결과가 다르다!)


np.float64(nan)

# Broadcasting
#### 브로드캐스팅
  - (기본적으로는) Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
  - **다른 Shape을 갖는 array 간 연산** 의 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
    
    
![](https://numpy.org/doc/stable/_images/broadcasting_1.png)

In [154]:
x = np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [155]:
np.random.seed(42)
y = np.random.rand(15).reshape(3, 5)
y

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497]])

In [156]:
x + y

array([[ 0.37454012,  1.95071431,  2.73199394,  3.59865848,  4.15601864],
       [ 5.15599452,  6.05808361,  7.86617615,  8.60111501,  9.70807258],
       [10.02058449, 11.96990985, 12.83244264, 13.21233911, 14.18182497]])

In [157]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)

In [158]:
a   # (4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [159]:
b  # (3,)

array([100, 101, 102])

In [160]:
# 덧셈 연산이 된다!
a + b


array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

# 🟦Boolean Indexing

In [161]:
# 'Boolean indexing ' !
# array 인덱싱 시, bool 리스트(aka. mask)를 전달하여 True인 경우만 필터링

# for 사용하지 않고도 array 에서 '조건'에 맞는 데이터만 추출 하는 기능

# 머신러닝 등에 있어서도 많이 사용



In [162]:
# 브로드캐스팅을 활용하여 array로 부터 bool list 얻기
#  - 예) 짝수인 경우만 찾아보기

np.random.seed(41)
x = np.random.randint(1, 100, size=10)
x

array([65, 36, 13, 99, 81, 66, 90, 24, 86, 27])

In [163]:
x % 2


array([1, 0, 1, 1, 1, 0, 0, 0, 0, 1])

In [164]:
even_mask = x % 2 == 0
even_mask

array([False,  True, False, False, False,  True,  True,  True,  True,
       False])

In [165]:
# 위와 같이 bool 값으로 이루어진 array 를 Mask 라고도 한다
# 위 결과, mask 를 변수에 담아 보겠습니다

# boolean mask 로 인덱싱!
print(x)
print(even_mask)

x[even_mask]


[65 36 13 99 81 66 90 24 86 27]
[False  True False False False  True  True  True  True False]


array([36, 66, 90, 24, 86])

In [166]:
# list 나 tuple 같은 iterable 도 bool mask 로 사용 가능.

print(x)

x[[True, True, True, True, False, False, False, False, False, True]]


[65 36 13 99 81 66 90 24 86 27]


array([65, 36, 13, 99, 27])

In [167]:
x[x > 30]

array([65, 36, 99, 81, 66, 90, 86])

## 다중조건 사용하기
 - 파이썬 논리 연산자인 and, or, not 키워드는 사용 불가
 - & ← AND
 - | ← OR

In [168]:
# ↓짝수이면서 30보다 작은 숫자들은?

In [169]:
x[(x % 2 == 0) & (x < 30)]


array([24])

## astype() 으로 변환

In [170]:
# 기억하시죠?
True, int(True), False, int(False)

(True, 1, False, 0)

In [171]:
True + True

2

In [172]:
# 🔹TODO

## 도전!  서울시 5월 일자별 평균기온

In [173]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6,
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9,
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5,
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

"""

도전]
Q1] 평균기온이 25도를 넘는 날의 수는?  => 21일
Q2] 평균기온이 25도를 넘는 날의 평균기온은? => 26.8도

.mean()
.sum()

"""
None

In [180]:
# by 조남호

daysAbove25dc = temp[temp > 25].size

avgTempAbove25dc = temp[temp > 25].mean() # 26.857... => 26.9
# 26.857 * 10 => 268.57 => trunc 268 / 10 => 26.8

print(f"평균기온이 25도를 넘는 날의 수는?  => {daysAbove25dc}일")
print(f"평균기온이 25도를 넘는 날의 평균기온은? => {int(avgTempAbove25dc * 10) / 10}도")

평균기온이 25도를 넘는 날의 수는?  => 21일
평균기온이 25도를 넘는 날의 평균기온은? => 26.9도


In [178]:
# By 우준영
print("Q1] 평균기온이 25도를 넘는 날의 수는?")
result1=temp[temp>25]
print(len(result1))

print("Q2] 평균기온이 25도를 넘는 날의 평균기온은? => 26.8도")
print(f"{result1.sum() / len(result1):.1f}")

Q1] 평균기온이 25도를 넘는 날의 수는?
21
Q2] 평균기온이 25도를 넘는 날의 평균기온은? => 26.8도
26.9


In [175]:
# ↑ for, while, if 등의 명시적인 제어문 사용하지 않고도
# numpy 만으로도 위 동작들 구현 가능.