In [ ]:
# 목표 : 앙상블 학습이 무엇인지 이해하고 다양한 학습 알고리즘을 실습을 통해 배웁니다
# 키워드 : 앙상블 학습, 램덤포레스트, 엑스트라 트리, 그레디언트 부스팅

# 핵심 패키지, 함수 :
#  RandomForestClassifier, ExtraTreesClassifier,
#  GradientBoostingClassifier, HistGradientBoostingClassifier

# 데이터셋 : wine.csv

In [ ]:
# Q] 가장 좋은 알고리즘이라는게 있을까?


# 정형 데이터 와 비정형 데이터

1. 정형데이터(Structured Data)
    - 정해진 틀 '스키마' 에 맞춰 저장된 데이터
    - 주로 행 과 열로 구성된 형태의 데이터
    - ex) CSV, 데이터베이스, 엑셀 파일 ..
    
    
1. 비정형 데이터 (Unstructured Data)
    - 정형데이터 형태로 표현하기 어려운 데이터들
    - ex) 책, 글 텍스트, 사진, 음악

1. 반정형 데이터 (Semi-Structured Data)
    - 고정된 틀은 없지만, 구조는 파악할수 있는 데이터
    - 스키마가 유연함
    - ex) JSON, XML, HTML, NoSQL

# 앙상블 학습이란
(ensemble learning)

더 좋은 예측 결과를 만들기 위해 '여러 개의 모델'을 훈련하는 머신러닝 알고리즘

In [ ]:
# 정형데이타를 다룰때 가장 뛰어난 성과를 내는 알고리즘 => '앙상블 학습(ensemble learning)'

# 앙상블 학습 이란 '여러개의 모델'을 훈련하여 더 좋은 예측 결과를 내는 머신러닝 알고리즘
# ※ 대부분 '결정트리' 기반으로 만들어진다..

# 이번에 배울 알고리즘들이 앙상블 학습에 속합니다!

In [ ]:
# 반면, 비정형 데이터는 어떤 알고리즘 사용?  --> '신경망 알고리즘'
# 비정형 데이터는 '규칙성' 을 찾기 어려워서 전통적인 머신러닝 알고리즘으로는 모델만들기 어렵다.


# 랜덤 포레스트 Random Forest

In [ ]:
# Decision Tree : 나무
# Random Forest : decision tree 를 랜덤하게 만들어 '숲' 을 만든다.
#                각 decision tree 의 예측을 사용해 '최종예측'을 만든다


![](https://www.dropbox.com/scl/fi/2n5p907zc2lot5538u9on/random_forest01.png?rlkey=gbkjkarjg549yxb5axc5rel7w&st=21k745aw&dl=1)
![](https://www.dropbox.com/scl/fi/18364zffb41q6v5lx5phq/random_forest02.png?rlkey=g8ig06vkizuv7gqzvm0snccxy&st=2u3mohn7&dl=1)

## 부트스트랩 샘플 (bootstrap sample)

In [ ]:
# 램덤포레스트는 각 트리를 훈련하기 위핸 데이터를 아래와 같이 랜덤하게 만든다.

# 입력한 훈련데이터에서 '랜덤하게 샘플을 추출'하여 훈련데이터를 만드는데.
# 이때 한 샘플이 '중복' 되어 추출될 수도 있습니다.
# 이런식으로 만들어진 샘플을 부트스트랩 샘플 이라 한다.

# 기본적으로 부트스트램 샘플은 '훈련세트와 같은 크기' 로 만든다.
# ex) 1000개가 들어있는 가방에서 1000개의 샘플을 뽑기 (중복허용)


# ■ 부트스트랩 이란 무엇인가?
# 보통 부트스트랩 방식이라고도 하는데, '데이터세트에서 중복을 허용하여 데이터를 샘플링하는 방식'을 의미함.
# 본문에서 설명한 것처럼 가방에 1000개의 샘플이 있을때 먼저 1개를 뽑고, 다시 가방에 넣어
# 그 다음 샘플을 뽑는 방식을 뜻하는 거죠.
# 부트스트랩 샘플이란 결국 부트스트랩 방식으로 샘플링하여 분류한 데이터라는 의미입니다.

## RandomForestClassifier

In [ ]:
# 트리에선 각 노드를 분할할때 '전체특성' 중에서 '일부특성' 을 '무작위' 로 고른다음 '최선의 분할' 을 찾습니다.

# RandomForestClassifier 는 기본적으로 '전체특성의 개수의 제곱근만큼' 의 특성을 선택함.
#    ex) 전체 4개의 특성이 있다면 -> 노드마다 2개를 램덤하게 선택하여 사용.

# RandomForestRegressor 는 '전체특성을 사용'


![](https://www.dropbox.com/scl/fi/fq6k4jmptdwegn6j4xxec/random_forest03.jpg?rlkey=bmlmfus9wpie4zf3wkax2qeh7&st=2xjmrd5a&dl=1)

In [ ]:
# 사이킷럿의 랜덤포레스트는 기본적으로 100개의 결정트리를 위와 같은 방식으로 훈련함.

# 최종 예측은!
#  '분류' 일때는 각 트리의 클래스별 확률을 평균하여 가장 높은 확률을 가진 클래스를 예측으로 삼습니다
#  '회귀' 일때는 단순히 각 트리의 예측을 평균합니다.


In [ ]:
# 랜덤 포레스트는 랜덤하게 선택한 샘플과 특성을 사용하기 때문에
# 훈련세트에 과대적합되는 것을 막아주고
# 검증세트와 테스트세트에서 안정적인 성능을 얻을 수 있습니다.
# 종종 기본 매개변수 설정 만으로도 아주 좋은 결과를 냅니다.


In [ ]:
# ↓ RandomForestClassifier 클래스를 화이트 와인을 분류하는 문제에 적용해 보죠.
# 먼저 이전 절에서 했던 것처럼 와인 데이터셋을 판다스로 불러오고 훈련 세트와 테스트 세트로 나눕니다.

## 데이터 준비

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [2]:
base_path = r'/content/drive/MyDrive/KoreaIT (코리아it)/260113 💚AI MCP 에이전트 S1/[MCP_Agent]/dataset(MCP2601)'

In [3]:
file_path = os.path.join(base_path, 'wine.csv')
wine_df = pd.read_csv(file_path)

wine_df

,alcohol,sugar,pH,class
0,9.4,1.9,3.51,0.0
1,9.8,2.6,3.20,0.0
2,9.8,2.3,3.26,0.0
3,9.8,1.9,3.16,0.0
4,9.4,1.9,3.51,0.0
...,...,...,...,...
6492,11.2,1.6,3.27,1.0
6493,9.6,8.0,3.15,1.0
6494,9.4,1.2,2.99,1.0
6495,12.8,1.1,3.34,1.0


In [4]:
data = wine_df[['alcohol', 'sugar', 'pH']].to_numpy()
target = wine_df['class'].to_numpy()

In [5]:
from sklearn.model_selection import train_test_split

# train:test = 8:2 로 분리
train_input, test_input, train_target, test_target = train_test_split(
    data, target, test_size=0.2, random_state=42)

## 교차검증 cross_validate

In [ ]:
# cross_validate()
#  return_train_score=  를 True 로 지정하면, 검증 점수뿐 아니라 훈련세트에 대한 점수로 같이 리턴함.
#                               => 훈련세트와 검증세트 점수를 비교하여 overfit 파악 용이.

In [6]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

```python
class sklearn.ensemble.RandomForestClassifier(
  n_estimators=100,
  *,
  criterion='gini',
  max_depth=None,
  min_samples_split=2,
  min_samples_leaf=1,
  min_weight_fraction_leaf=0.0,
  max_features='sqrt',
  max_leaf_nodes=None,
  min_impurity_decrease=0.0,
  bootstrap=True,
  oob_score=False, # out of bag 샘플을 사용한 평가점수
  n_jobs=None,  # 학습에 사용하는 cpu 코어개수
  random_state=None, # 랜덤 시드
  verbose=0,
  warm_start=False,
  class_weight=None,
  ccp_alpha=0.0,
  max_samples=None,
  monotonic_cst=None)
````

↑ 기본적으로 DecisionTreeClassifier 의 거의 대부분의 매개변수들을 가지고 있다

In [7]:
# cross validate 실행
rf = RandomForestClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(
    rf,
    train_input, train_target,
    return_train_score=True,
    n_jobs=-1,
)

scores
# ↓ 기본적으로 cv=None (5 fold)

{'fit_time': array([0.45537448, 0.46321011, 0.47710276, 0.50873804, 0.28823709]),
 'score_time': array([0.04832363, 0.03550029, 0.03422427, 0.03575158, 0.02435255]),
 'test_score': array([0.88461538, 0.88942308, 0.90279115, 0.88931665, 0.88642926]),
 'train_score': array([0.9971133 , 0.99663219, 0.9978355 , 0.9973545 , 0.9978355 ])}

In [9]:
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9973541965122431 0.8905151032797809


## 특성중요도 feature_importances_

In [ ]:
# 랜덤포레스트의 '특성중요도' 는 각 결정트리의 특성중요도를 취합한 거다


In [10]:
rf.fit(train_input, train_target)
print(rf.feature_importances_)

[0.23167441 0.50039841 0.26792718]


In [ ]:
#         알코올,       당도,        pH
#      [0.12345626, 0.86862934, 0.0079144 ]   <- DecisionTree 이전단원!

# array([0.23167441, 0.50039841, 0.26792718])   <- RandomForest

# 당도의 중요도는 감소하고, 알코올과 ph 중요도가 상승했다.
# 이유는!  랜덤포레스트라 '특성의 일부' 를 '랜덤' 하게 선택하여 결정트리를 훈련함!
#   => 그 결과 하나의 특성에 과도하게 집중하지 않고, 더 많은 특성이 훈련에 기여할 기회를 얻게 됨.
#   => overfit 을 줄이고 일반화 성능을 높일수 있을것으로 기대.


## OOB (out of bag) 샘플
부트스트랩 샘플에 포함되지 않고 남는 샘플

In [ ]:
# RandomForestClassifier 는 OOB 샘플을 활용하여 자체적으로 모델을 평가하는 기능이 있다

#  oob_score= 를 True 로 지정해야 한다


In [11]:
rf = RandomForestClassifier(
    oob_score=True,  # OOB 활용!
    n_jobs=-1, random_state=42)

rf.fit(train_input, train_target)
print(rf.oob_score_)


0.8934000384837406


# 엑스트라 트리
Extra Tree

## ExtraTreesClassifier

In [ ]:
# 엑스트라트리 가
# 랜덤포레스트와 비슷한점
#    - 기본적으로 100개의 결정트리 훈련
#    - 결정트리가 제공하는 대부분의 매개변수 지원
#    - 일부특성을 램덤하게 선택하여 노드 분할

# 랜덤포레스트와의 차이점!
#    - 부트스프램 샘플 사용하지 않는다!
#    - 결정트리 만들때 '전체세트' 사용.
#    - 노드를 분할할때 가장 좋은 분할을 찾는게 아니라 '무작위 분할'함!
#       - 사실 DecisionTreeClassifier 에서 splitter='random' 으로 지정한 결정트리가 바로 이거다.

# 하나의 결정트리였다면.. 무작위 분할은 성능이 낮아지지만
# 많은 트리를 앙상블 하면 overfit 억제하고 검증점수 높이는 효과 기대.


In [12]:
from sklearn.ensemble import ExtraTreesClassifier

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.ExtraTreesClassifier.html
```python
class sklearn.ensemble.ExtraTreesClassifier(
  n_estimators=100,
  *,
  criterion='gini',
  max_depth=None,
  min_samples_split=2,
  min_samples_leaf=1,
  min_weight_fraction_leaf=0.0,
  max_features='sqrt',
  max_leaf_nodes=None,
  min_impurity_decrease=0.0,
  bootstrap=False,
  oob_score=False,
  n_jobs=None,
  random_state=None,
  verbose=0,
  warm_start=False,
  class_weight=None,
  ccp_alpha=0.0,
  max_samples=None,
  monotonic_cst=None)
```

In [13]:
et = ExtraTreesClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(et, train_input, train_target, return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9974503966084433 0.8887848893166506


In [ ]:
|# 일반적으론,
# 엑스트라트라가 무작위성이 좀 더 크기 때문에 랜덤포레스트보다는 더 많은 결정트리 훈련해야 한다.
# 램덤하게 노드 분할하기때문에 계산속도는 상대적으로 빠르다


In [14]:
# 엑스트라 트리도 랜덤 포레스트와 마찬가지로 특성 중요도를 제공합니다.
et.fit(train_input, train_target)
print(et.feature_importances_)

[0.20183568 0.52242907 0.27573525]


In [ ]:
# 순서는 [알코올 도수, 당도, pH] 인데,

#    알코올       당도       pH
# [0.12345626, 0.86862934, 0.0079144 ]  <- DecisionTree

# [0.23167441 0.50039841 0.26792718]   <- RandomForest

# [0.20183568 0.52242907 0.27573525]   <- ExtraTrees

# ↑ 결과를 보면 엑스트라 트리도 결정 트리보다 당도에 대한 의존성이 작습니다.

In [ ]:
# ※ 엑스트라 트리의 '회귀' 버전은 ExtraTreesRegressor 입니다.

# 그레디언트 부스팅
Gradient Boosting

## GradientBoostingClassifier

In [ ]:
# GradientBoostingClassifier 는 얕은깊이의 결정트리 사용
#    (기본적으로) 깊이3 결정트리 x 100개 사용
#    깊이가 얕기에 오버핏 억제에 유리, 높은 일반화 성능 기대.


In [ ]:
# '경사하강법' 을 사용하여 트리를 앙상블에 추가함.

# 그레디언트는 무엇이? 낮을 곳을 찾아 이동하게 되나?
#  '그레디언트 부스팅' 은 결정트리를 '계속 추가'하면서 가장 낮은 곳을 찾아 이동.
#   손실함수의 낮은곳으로 '천천히 조금씩' 이동하듯이
#   그레디언트 부스팅도 '깊이가 얕은 트리를 사용'하여  조금씩 낮은곳으로 이동.


In [15]:
from sklearn.ensemble import GradientBoostingClassifier

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingClassifier.html

```python
class sklearn.ensemble.GradientBoostingClassifier(
  *,
  loss='log_loss',   # 손실함수
  learning_rate=0.1, # 학습률  
  n_estimators=100,  # 트리의 개수
  subsample=1.0,
  criterion='friedman_mse',
  min_samples_split=2,
  min_samples_leaf=1,
  min_weight_fraction_leaf=0.0,
  max_depth=3,
  min_impurity_decrease=0.0,
  init=None,
  random_state=None,
  max_features=None,
  verbose=0,
  max_leaf_nodes=None,
  warm_start=False,
  validation_fraction=0.1,
  n_iter_no_change=None,
  tol=0.0001,
  ccp_alpha=0.0)
```

In [16]:
gb = GradientBoostingClassifier(random_state=42)  # n_jobs= 없다!
scores = cross_validate(gb, train_input, train_target,
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))


0.8881086892152563 0.8720430147331015


In [ ]:
#  ↑ overfit 이 많이 억제되고 있다.

#  ↓ 그레디언트 부스팅은 결정트리의 개수를 늘려도 overfit 에 강하다.


In [17]:
# 트리의 개수를 500개로 늘리고 다시!
gb = GradientBoostingClassifier(
    n_estimators=500, # 트리의 개수를 늘려보자  (기본값 100)
    learning_rate=0.2,  # 학습률 증가 (기본값 0.1)
    random_state=42,
)

scores = cross_validate(gb, train_input, train_target, return_train_score=True, n_jobs=-1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))




0.9464595437171814 0.8780082549788999


In [ ]:
# ↑결정트리의 개수를 x5배나 늘렸지만, 그에 비해선 overfit 을 잘 억제하고 있다.


In [18]:
# 그레디언트 부스팅도 특성 중요도를 제공합니다.
gb.fit(train_input, train_target)
print(gb.feature_importances_)


[0.15887763 0.6799705  0.16115187]


In [ ]:
"""
   알코올       당도        pH
0.23167441, 0.50039841, 0.26792718   <= Random Forest

0.20183568  0.52242907 0.27573525     <= Extra Tree

0.15872278, 0.68010884, 0.16116839   <= Gradient Boosting (파라미터)

↑ 결과에서 볼수 있듯이 그레디언트 부스팅이 램덤포레스트보다 일부 특성(당도)에 더 집중합니다.
"""
None

## subsample= 파라미터

In [ ]:
# subsample: 트리훈련에 사용할 훈련세트의 비율을 정함.
#       기본값 1.0 => '전체훈련세트' 사용
#       1.0보다 작으면 => '훈련세트의 일부' 사용
#              => 확률적 경사하강법, 미니배치경사하강법 과 비슷하게
#                 경사 하강법 단계마다 일부 샘플을 랜덤하게 선택하여 진행.


In [ ]:
# 일반적으로 그레디언트 부스팅이 랜덤포레스트보다 성능은 좀더 높지만, 훈련속도가 느리다.
#  이유는!  n_jobs 매개변수가 없다.  (병렬 프로세싱 안된다...)
#  순서대로 트리를 추가해가면서 훈련하기 때문이다.


# 히스토그램 기반 그레디언트 부스팅
Histogram-based Gradient Boosting

## HistGradientBoostingClassifier

In [ ]:
# 입력데이터의 특성을 '구간' 으로 나눈다.  (기본 256개의 구간)
# => 노드를 분할할때 최적의 분할을 매우 빠르게 찾을수 있다.

# 256개의 구간중에서 하나는 떼어놓는다 => 누락된 값을 위해서 사용하기 위함.

# 기본 매개변수에서 안정적인 성능
# 트리의 개수를 지정하는데 n_estimators= 대신에  max_iter= 사용.
# 부스팅 반복횟수를 지정하는 max_iter 사용.  <- 성능을 높일때 이 매개변수를 조정해보세요.


In [19]:
from sklearn.ensemble import HistGradientBoostingClassifier

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.HistGradientBoostingClassifier.html

```python
class sklearn.ensemble.HistGradientBoostingClassifier(
  loss='log_loss',
  *,
  learning_rate=0.1,
  max_iter=100, # 부스팅 반복 횟수
  max_leaf_nodes=31,
  max_depth=None,
  min_samples_leaf=20,
  l2_regularization=0.0,
  max_features=1.0,
  max_bins=255,
  categorical_features='from_dtype',
  monotonic_cst=None,
  interaction_cst=None,
  warm_start=False,
  early_stopping='auto',
  scoring='loss',
  validation_fraction=0.1,
  n_iter_no_change=10,
  tol=1e-07,
  verbose=0,
  random_state=None,
  class_weight=None)
```

In [20]:
hgb = HistGradientBoostingClassifier(random_state=42)
scores = cross_validate(hgb, train_input, train_target, return_train_score=True, n_jobs=-1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))



0.9321723946453317 0.8801241948619236


In [ ]:
"""
0.8881086892152563 0.8720430147331015  <- Gradient Boosting
0.9321723946453317 0.8801241948619236  <- HistGradientBoosting

↑ 과대적합을 잘 억게 하면서 그레디언트 부스팅보다 조금 더 높은 성능을 제공합니다.
"""
None

## 특성중요도 permutation_importance()

In [ ]:
# 특성중요도 : permutation_importance() 사용
#  특성을 하나씩 램덤하게 섞어서 모델의 성능이 변화하는지 관찰한 후 어떤 특성이 중요한지 계산
#  n_repeats=  : 랜덤하게 섞을 횟수 지정 (디폴트 5)


In [21]:
from sklearn.inspection import permutation_importance

https://scikit-learn.org/stable/modules/generated/sklearn.inspection.permutation_importance.html

```python
sklearn.inspection.permutation_importance(
  estimator,
  X,
  y,
  *,
  scoring=None,
  n_repeats=5, # 랜덤하게 섞을 횟수
  n_jobs=None,
  random_state=None,
  sample_weight=None,
  max_samples=1.0)
```


In [ ]:
# 먼저 히스토그램 기반 그레디언트 부스팅 모델을 훈련하고 '훈련 세트'에서 특성 중요도 계산해보겠습니다
# n_repeats= 매개변수는 랜덤하게 섞을 횟수를 지정합니다.
#    여기서는 10으로 지정 하겠습니다. (디폴트값은 5 입니다)


In [22]:
# '훈련 세트'에서 특성 중요도 계산
hgb.fit(train_input, train_target)
result = permutation_importance(hgb, train_input, train_target, n_repeats=10,
                                random_state=42, n_jobs=-1)

print(result.importances_mean)


[0.08876275 0.23438522 0.08027708]


In [ ]:
"""
   알코올       당도        pH
0.23167441, 0.50039841, 0.26792718   <= Random Forest

0.20183568 0.52242907 0.27573525     <= Extra Tree

0.15872278, 0.68010884, 0.16116839   <= Gradient Boosting (파라미터)

0.08876275, 0.23438522, 0.08027708   <= Hist Gradient Boosting


permutation_importance() 함수가 리턴하는 객체는 반복하여 얻은
특성 중요도 (importance), 평균 (importances_mean), 표준편차 (importances_std) 를 담고 있습니다.

"""
None



In [23]:
# '테스트 세트'에서 특성 중요도 계산
result = permutation_importance(hgb, test_input, test_target, n_repeats=10,
                                random_state=42, n_jobs=-1)
print(result.importances_mean)


[0.05969231 0.20238462 0.049     ]


In [24]:
# 성능 확인
hgb.score(test_input, test_target)


0.8723076923076923

## XGBoost

In [ ]:
# XGBoost 는 다양한 부스팅 알고리즘 지원
# tree_method=  를 'hist' 로 지정하면
# 히스토그램 기반 그레디언트 부스팅 을 사용할수 있다


In [25]:
# 설치]
#   pip install xgboost
#   Anaconda 환경 : conda install xgboost
#   colab 에서는 바로 사용 가능
# https://xgboost.ai/
# https://xgboost.readthedocs.io/en/latest

from xgboost import XGBClassifier

In [26]:
xgb = XGBClassifier(tree_method='hist', random_state=42)
scores = cross_validate(xgb, train_input, train_target, return_train_score=True, n_jobs=-1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))


0.9567059184812372 0.8783915747390243


## LightGBM

In [27]:
# 설치]
#   pip install lightgbm
#   Anaconda 환경 : conda install lightgbm
#   colab 에서는 바로 사용 가능

#  https://github.com/microsoft/LightGBM
#  https://lightbgm.readthedocs.io/en/latest  <= 온라인 문서


from lightgbm import LGBMClassifier

In [28]:
lgb = LGBMClassifier(random_state=42)
scores = cross_validate(lgb, train_input, train_target, return_train_score=True, n_jobs=-1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))


0.935828414851749 0.8801251203079884


# 앙상블 학습 (정리)

앙상블 학습은 **'정형 데이터'**에서 가장 뛰어난 성능을 내는 머신러닝 알고리즘 중 하나입니다

↓대표적인 앙상블 학습들

1. 사이킷럿
    1. 랜덤포레스트 : 부트스트랩 샘플 사용. 대표 앙상블 학습알고리즘
    1. 엑스트라 트리 : 결정트리의 노드를 랜덤하게 분할함
    1. 그레디언트 부스팅 : 이전 트리의 손실을 보완하는 식으로 얕은 결정 트리를 연속적으로 추가함
    1. 히스토그램 기반 그레디언트 부스팅 : 훈련 데이터를 256개 정수 구간으로 나누어 빠르고 높은 성능을 냄
    
1. 그 밖의 라이브러리
    1. XGBoost
    1. LightGBM